name: Build and Test Struct Definer Gem
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'
        bundler-cache: true
    - name: Build gem
      run: |
        gem build struct_definer.gemspec
        mkdir -p pkg
        mv struct_definer-*.gem pkg/
    - name: Publish gem to GitHub Packages
      env:
        GEM_HOST_API_KEY: ${{ secrets.MY_PAT }}
      run: gem push --host https://rubygems.pkg.github.com/y2kstack struct_definer-*.gem
    - name: Debug secrets
      run: echo "GEM_HOST_API_KEY is ${GEM_HOST_API_KEY:+set}"
    - name: Install dependencies
      run: bundle install
    - name: Run tests
      run: |
        bundle exec ruby -e "require 'struct_definer'; user = StructDefiner::User.new(name: 'Test', email: 'test@example.com'); puts user.serialize"