name: Build and Test Struct Definer Gem
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'
        bundler-cache: true
    - name: Configure GitHub Packages authentication
      env:
          GEM_HOST_API_KEY: ${{ secrets.GITHUB_TOKEN }}
      run: |
          gem build struct_definer.gemspec
          gem push pkg/*.gem --host https://rubygems.pkg.github.com/y2kstack
    - name: Install dependencies
      run: bundle install
    - name: Run tests
      run: |
        bundle exec ruby -e "require 'struct_definer'; user = StructDefiner::User.new(name: 'Test', email: 'test@example.com'); puts user.serialize"