name: Build and Test Struct Definer Gem
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'
        bundler-cache: true
    - name: Configure GitHub Packages authentication
      run: |
        mkdir -p ~/.gem
        echo "gem: --no-document" > ~/.gemrc
        echo ":github: Bearer ${{ secrets.PAT }}" > ~/.gem/credentials
        chmod 600 ~/.gem/credentials
        cat ~/.gem/credentials | sed 's/Bearer ./Bearer [REDACTED]/'
    - name: Build gem
      run: |
        mkdir -p pkg
        gem build struct_definer.gemspec --output pkg/struct_definer-${{ github.sha }}.gem
    - name: Publish gem to GitHub Packages
      run: gem push --key github --host https://rubygems.pkg.github.com/y2kstack pkg/struct_definer-.gem
    - name: Install dependencies
      run: bundle install
    - name: Run tests
      run: |
        bundle exec ruby -e "require 'struct_definer'; user = StructDefiner::User.new(name: 'Test', email: 'test@example.com'); puts user.serialize"